config/routes.rb
Rails.application.routes.draw do
  root "videos#index"

  resources :videos, only: [:index, :show, :update, :destroy] do
    get 'new', on: :collection
    get 'watched', on: :collection
    get 'saved', on: :collection
  end

  resources :channels, only: [:new, :create, :index, :destroy, :update] do
    get '/videos' => 'videos#new'
    get '/videos/new' => 'videos#new'
    get '/videos/watched' => 'videos#watched'
    get '/videos/saved' => 'videos#saved'
  end

  resource :login, only: [:new, :create, :destroy], controller: 'login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :videos, dependent: :destroy
  enum :last_fetch_status, [:no_attempt, :success, :failure]
end

app/models/video.rb
class Video < ApplicationRecord
  include Turbo::Broadcastable
  belongs_to :channel
  enum :status, [:unseen, :seen, :saved]
  after_destroy_commit -> { broadcast_remove_to :videos }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  private
  def ensure_logged_in
    if session[:user].nil?
      redirect_to new_login_path
    end
  end

  def login!
    session[:user] = :user
  end

  def logout!
    reset_session
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :ensure_logged_in
  before_action :set_channel

  def index
    query = if params[:filter]
              Channel.where('name LIKE ?', "%#{params[:filter]}%")
            else
              Channel.all
            end
    @pagy, @channels = pagy(query,  link_extra: 'data-turbo-frame="content" data-turbo-action="advance"')
    @selected = 'channels'
    @is_filter_request = params[:filter_request]
  end

  def create
    cmd = SubscribeToFeed.new(target_url: params[:target_url])
    @channel = cmd.perform
    if cmd.errors.any?
      @errors = cmd.errors
    else
      @errors = []
      query = Video.eager_load(:channel)
        .where(status: :unseen)
        .order(video_published_at: :desc)

      @pagy, @videos = pagy(query,  link_extra: 'data-turbo-frame="content" data-turbo-action="advance"')
      
      RefreshFeed.new(channel: @channel).perform
    end
  end

  def destroy
    @channel.destroy!
     Turbo::StreamsChannel.broadcast_update_to(
       :videos,
       target: 'new-video-count', 
       html: Video.where(status: :unseen).count
     )
  end

  def update
    RefreshFeed.new(channel: @channel).perform
  end

  def set_channel
    if params[:id]
      @channel = Channel.find(params[:id])
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def new
    render layout: false
  end

  def destroy
    logout!
    redirect_to new_login_path
  end

  def create
    username = Rails.application.credentials.username
    password = Rails.application.credentials.password

    success = [
      params[:username].present?,
      params[:password].present?,
      ActiveSupport::SecurityUtils.secure_compare(username, params[:username]),
      ActiveSupport::SecurityUtils.secure_compare(password, params[:password])
    ].all?

    if success
      login!
      redirect_to root_path
    else 
      flash[:error] = "Incorrect"
      render 'new', layout: false
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :ensure_logged_in
  before_action :set_channel, :set_video, :set_filter_request

  def index
    @selected = 'new'
    get_videos
  end

  def new
    @selected = 'new'
    get_videos
  end

  def watched
    @selected = 'watched'
    get_videos(status: :seen)
  end

  def saved
    @selected = 'saved'
    get_videos(status: :saved)
  end

  def update
    @video.update!(params.permit(:status))
  end

  def destroy
    @video.destroy!
  end

  private
  def set_channel
    if params[:channel_id]
      @channel = Channel.find(params[:channel_id])
    end
  end

  def set_video
    if params[:id]
      @video = Video.find(params[:id])
    end
  end

  def get_videos(status: :unseen)
    @pagy, @videos = pagy(query(status: status),  link_extra: 'data-turbo-frame="content" data-turbo-action="advance"')
    render :index
  end

  def query(status: :unseen)
    query = Video.eager_load(:channel)
      .where(status: status)
      .order(video_published_at: :desc)
    if @channel
      query = query.where(channel: @channel)
    end
    if params[:filter].present?
      query = query.where('videos.title LIKE ?', "%#{params[:filter]}%")
    end
    query
  end

  def set_filter_request
    @is_filter_request = params[:filter_request]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def tag_class(channel: )
    case channel.last_fetch_status
    when 'failure'
      'is-warning'
    when 'success'
      'is-info'
    else
      'is-dark'
    end
  end

  def nav_class(id:, selected:)
    if id == selected
      'level-item nav-selected is-underlined'
    else
      'level-item'
    end
  end

  def filter_path_helper(selected:, channel:)
    if selected == 'channels'
      return channels_path
    end

    if channel.nil? 
      if selected == 'watched'
        watched_videos_path
      elsif selected == 'saved'
        saved_videos_path
      else
        videos_path
      end
    else
      if selected == 'watched'
        channel_videos_watched_path(@channel)
      elsif selected == 'saved'
        channel_videos_saved_path(@channel)
      else
        channel_videos_path(@channel)
      end
    end
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/application/_favicon.html.erb
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🥔</text></svg>" />

app/views/application/_nav.html.erb
<nav id="main-nav" class="level">
  <div class="level-left">
    <div class="level-item">
      <%= form_with(url: filter_path_helper(channel: channel, selected: selected), method: :get, data: { controller: 'filter', turbo_action: 'advance', turbo_frame: 'content'}) do |f| %>
        <%= f.text_field :filter, class: 'input', placeholder: 'Filter', value: params[:filter], data: { action: 'input->filter#debouncedSubmit' } %>
        <%= f.hidden_field :filter_request, value: true %>
      <% end %>
    </div>
  </div>
    <%= render partial: 'application/right_nav', locals: { selected: @selected, channel: @channel } %>
</nav>

app/views/application/_nothing_here.html.erb
<article class="message">
  <div class="message-header">
    <p>Nothing Here</p>
  </div>
  <div class="message-body">
    You'll have to find something else to do with with your time I guess 😢. 
  </div>
</article>

app/views/application/_right_nav.html.erb
  <div id="right-nav" class="level-right">
    <% if channel %>
      <div class="level-item">
        <%= button_to "/videos/#{selected}", class: 'button is-rounded', method: :get, data: { turbo_frame: 'content', turbo_action: 'advance' } do %>
            <span class="icon">
              <i class="gg-close"></i>
            </span>
            <span>
              <%= channel.name %>
            </span>
        <% end %>
      </div>
    <% end %>
    <p class="<%= nav_class(id: 'new', selected: selected) %>">
    <%= link_to @channel? channel_videos_path(@channel) : root_path, data: { turbo_frame: 'content', turbo_action: 'advance' } do %>
      New
    <% end %>
    </p>
    <p class="<%= nav_class(id: 'watched', selected: selected) %>">
    <%= link_to @channel ? channel_videos_watched_path(@channel) : watched_videos_path, data: { turbo_frame: 'content', turbo_action: 'advance' } do %>
      Watched
    <% end %>
    </p>
    <p class="<%= nav_class(id: 'saved', selected: selected) %>">
    <%= link_to @channel ? channel_videos_saved_path(@channel) : saved_videos_path, data: { turbo_frame: 'content', turbo_action: 'advance' } do %>
      Saved
    <% end %>
    </p>
    <p class="<%= nav_class(id: 'channels', selected: selected) %>">
    <%= link_to channels_path, data: { turbo_frame: 'content', turbo_action: 'advance' } do %>
      Channels
    <% end %>
    </p>
    <div class="level-item">
      <div class="not-loading">
        <%= button_to new_channel_path, class: 'button is-primary', method: :get, data: { turbo_frame: 'notice' }  do %>
          <span class="icon">
            <i class="gg-math-plus"></i>
          </span>
          <span>Add</span>
        <% end %>
      </div>
      <%= button_to login_path, class: 'button is-text', title: 'Logout', method: :delete do %>
        <span class="icon"> <i class="gg-log-out"></i> </span>
      <% end %>
    </div>
  </div>

app/views/channels/_channel.html.erb
<div id="<%= dom_id channel %>" class="block box has-background-grey-lighter" data-exit-animation-class="animate-slide-out">
  <div class="columns is-vcentered">
  <div class="column is-8">
    <p class="has-text-grey-darker">
      <%= link_to channel_videos_path(channel), class: 'has-text-grey-darker', data: { turbo_frame: 'content', turbo_action: 'advance' } do %>
        <strong><%= channel.name %></strong>
      <% end %>
    </p>
    <%= render partial: 'status_tag', locals: { channel: channel } %>
  </div>
  <div class="column">
    <%= turbo_frame_tag dom_id(channel, :controls) do %>
      <span class="buttons are-medium is-right">
        <%= button_to channel.youtube_url, title: 'Channel Link', form: {target: '_blank'}, method: :get, class: 'button is-text' do %>
          <span class="icon"><i class="gg-external"></i></span>
        <% end %>
        <div class="control not-loading">
          <%= button_to channel_path(channel), title: 'Refresh', class: 'button is-text', method: :put do %>
            <span class="icon"><i class="gg-sync"></i></span>
          <% end %>
        </div>
        <div class="loading">
          <button class="button is-loading">
            <span class="icon"><i class="gg-sync"></i></span>
          </button>
        </div>
        <%= button_to channel_path(channel), title: 'Delete', class: 'button is-text', method: :delete do %>
          <span class="icon"><i class="gg-trash"></i></span>
        <% end %>
      </span>
    <% end %>
  </div>
  </div>
</div>

app/views/channels/_channels.html.erb
<% if channels.size == 0 %>
  <%= render 'application/nothing_here' %>
<% else %>
  <%= render channels %>
  <%== pagy_bulma_nav(pagy) %>
<% end %>

app/views/channels/_status_tag.html.erb
<span id="<%= dom_id(channel, :last_updated) %>" class="tag <%= tag_class(channel: channel) %> is-small">
  Last Update - <%= channel.last_fetch_attempt.nil? ? 'Never' : time_ago_in_words(channel.last_fetch_attempt) %>
</span>

app/views/channels/create.turbo_stream.erb
<%= turbo_stream.replace 'notice' do %>
  <% animate_out_class = @errors.none? ? 'animate-expand-out-slow' : '' %>
  <div data-controller="closeable" class='animate-expand-in' data-closeable-exit-class-value='animate-fade-out'>
    <% notification_type = @errors.none? ? 'is-primary' : 'is-warning' %>
    <div class="notification block <%= notification_type %>">
      <button class="delete" data-action="click->closeable#close"></button>
      <% if @errors.none? %>
        Subscribed to <%= @channel.name %>
      <% else %>
        <%= simple_format(@errors.join("\n")) %>
      <% end %>
    </div>
    <div class="block"></div>
  </div>
<% end %>

<% if @errors.none? %>
  <%= turbo_stream.replace 'video-list-items',  partial: 'videos/videos', locals: { videos: @videos, pagy: @pagy } %>
<% end %>

app/views/channels/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@channel) %>

app/views/channels/index.html.erb
<%= turbo_frame_tag 'content' do %>
  <div class="animate-slide-in">
    <% if @is_filter_request %>
      <%= turbo_stream.replace 'right-nav', partial: 'application/right_nav', locals: { selected: @selected, channel: nil } %>
    <% else %>
      <%= turbo_stream.replace 'main-nav', partial: 'application/nav', locals: { selected: @selected, channel: nil} %>
    <% end %>
    <%= render partial: 'channels/channels', locals: { channels: @channels, pagy: @pagy } %>
  </div>
<% end %>

app/views/channels/new.html.erb
<%= turbo_frame_tag 'notice' do %>
  <div class="modal is-active" data-closeable-exit-class-value="animate-fade-out" data-controller="closeable" data-action="keyup@document->closeable#handleKeyup">
    <div class="modal-background animate-fade-in" data-action="click->closeable#close"></div>
    <div class="modal-content">
      <div class="box has-background-light animate-expand-in">
        <%= form_with url: channels_path, method: :post do |f| %>
          <div class="field has-addons">
            <div class="control is-expanded">
              <%= f.text_field :target_url, class: 'input', placeholder: 'Channel or Video URL' %>
            </div>
            <div class="control not-loading">
              <%= f.submit "Subscribe", class: 'button is-primary' %>
            </div>
            <div class="control loading">
              <button class="button is-primary is-loading">Subscribe</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/channels/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@channel, :last_updated), partial: 'status_tag', locals: { channel: @channel } %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperTuber</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'favicon' %>

    <link href='https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css' rel='stylesheet'>
    <link href='https://css.gg/css?=math-plus|check-o|undo|heart|trash|close|sync|external|log-out' rel='stylesheet'>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= turbo_stream_from :videos %>
    <div class="columns">
      <div class="column is-10 is-offset-1">
        <section class="section">
          <%= render partial: 'application/nav', locals: { selected: nil, channel: nil } %>
          <%= turbo_frame_tag 'notice' do %>
            <div id="notice"></div>
          <% end %>
          <%= yield %>
        </section>
      </div>
    </div>
  </body>
</html>

app/views/login/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperTuber</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'favicon' %>

    <link href='https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css' rel='stylesheet'>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <section class="section is-large">
      <div class="columns">
        <div class="column is-offset-two-fifths is-3">
          <% if flash[:error] %>
            <div class="notification is-danger is-light">
              Wrong
            </div>
          <% end %>
          <%= form_with url: login_path, method: :post, class: 'box' do |f| %>
            <div class="field">
              <div class="control">
                <%= f.text_field :username, placeholder: 'Username', class: 'input' %>
              </div>
            </div>
            <div class="field">
              <div class="control">
                <%= f.text_field :password, type: 'password', placeholder: 'Password', class: 'input' %>
              </div>
            </div>
            <div class="field is-grouped is-grouped-right">
              <%= f.submit "Login", class: 'button is-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>" class="block box has-background-grey-lighter" data-exit-animation-class="animate-slide-out">
  <div class="media">
    <%= turbo_frame_tag dom_id(video, :watch) do %>
      <%= link_to video_path(video) do %>
        <figure class="media-left">
          <div class="crop video-thumbnail">
            <img src="<%= video.thumbnail_url %>" alt="<%= video.title %>">
          </div>
        </figure>
      <% end %>
    <% end %>
    <div class="media-content">
      <div class="content">
        <p>
        <%= link_to video.youtube_url, class: 'video-youtube-link has-text-grey-darker' do %>
          <strong><%= video.title %></strong>
        <% end  %>
        <br/>
        <%= link_to "/channels/#{video.channel.id}/videos", class: 'has-text-grey is-underlined', data: { turbo_frame: 'content', turbo_action: 'advance' } do %>
          <small><%= video.channel.name %> - <%= time_ago_in_words(video.video_published_at) %> ago</small>
        <% end %>
        </p>
        <p class="has-text-grey-darker is-size-6">
        <%= simple_format(video.description.truncate(200, separator: /\s/)) %>
        </p>
      </div>
    </div>
  </div>
  <div class="buttons is-right are-medium action-buttons">
    <% if video.unseen? || video.saved? %>
      <%= button_to video_path(video), title: 'Mark as watched', class: 'button is-text', method: :put, params: { status: :seen } do %>
        <span class="icon"><i class="gg-check-o"></i></span>
      <% end %>
    <% end %>
    <% if video.seen? %>
      <%= button_to video_path(video), title: 'Mark as new', class: 'button is-text', method: :put, params: { status: :unseen } do %>
        <span class="icon"><i class="gg-undo"></i></span>
      <% end %>
    <% end %>
    <% if !video.saved? %>
      <%= button_to video_path(video), title: 'Save for later', class: 'button is-text', method: :put, params: { status: :saved } do %>
        <span class="icon"><i class="gg-heart"></i></span>
      <% end %>
    <% end %>
    <%= button_to video_path(video), title: 'Delete', class: 'button is-text', method: :delete do %>
      <span class="icon"><i class="gg-trash"></i></span>
    <% end %>
  </div>
</div>

app/views/videos/_videos.html.erb
<% if videos.size == 0 %>
  <%= render 'application/nothing_here' %>
<% else %>
  <%= render videos %>
  <%== pagy_bulma_nav(pagy) %>
<% end %>

app/views/videos/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@video) %>

app/views/videos/index.html.erb
<%= turbo_frame_tag 'content' do %>
  <div class="animate-slide-in">
    <% if @is_filter_request %>
      <%= turbo_stream.replace 'right-nav', partial: 'application/right_nav', locals: { selected: @selected, channel: @channel } %>
    <% else %>
      <%= turbo_stream.replace 'main-nav', partial: 'application/nav', locals: { selected: @selected, channel: @channel } %>
    <% end %>
    <div id='video-list-items'>
      <%= render partial: 'videos/videos', locals: { videos: @videos, pagy: @pagy } %>
    </div>
  </div>
<% end %>

app/views/videos/show.html.erb
<%= turbo_frame_tag dom_id(@video, :watch) do %>
  <figure class="media-left">
    <div class="crop">
      <iframe width="480" height="270" src="https://www.youtube-nocookie.com/embed/<%= @video.youtube_video_id %>?autoplay=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </div>
  </figure>
<% end %>

app/views/videos/update.turbo_stream.erb
<%= turbo_stream.remove dom_id(@video) %>